from concurrent.futures import ThreadPoolExecutor, as_completed
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage
from langgraph.graph import StateGraph, START, END
import json
from pydantic import ValidationError

from src.llm.gateway import get_llm
from src.llm.structured_output import build_json_instruction, unwrap_schema_echo
from src.models.macro import MacroSummary
from src.graph.messages_state import AgentMessagesState

from src.tools.macro.crude import get_crude_price
from src.tools.macro.fii_dii import get_fii_dii_flows
from src.tools.macro.gold import get_gold_price
from src.tools.macro.india_market import get_india_market_summary
from src.tools.macro.inflation import get_inflation_data
from src.tools.macro.rbi import get_rbi_updates
from src.tools.macro.us_market import get_us_market_summary
from src.tools.macro.usd_inr import get_usd_inr_rate
from src.tools.firecrawl.macro_news import search_macro_news_firecrawl
from src.tools.tavily.macro_news import search_macro_news_tavily
from src.tools.common.normalization import deduplicate_article_dicts, utc_now_iso

TOOLS = [
    get_fii_dii_flows,
    get_crude_price,
    get_us_market_summary,
    get_india_market_summary,
    get_usd_inr_rate,
    get_inflation_data,
    get_gold_price,
    get_rbi_updates,
    search_macro_news_tavily,
    search_macro_news_firecrawl,
]


class MacroAgent:
    def __init__(self):
        # Plain LLM for final JSON formatting
        self.formatter_llm = get_llm(agent_name="MacroAgent")

        # Graph builder
        builder = StateGraph(AgentMessagesState)

        builder.add_node("collect_data_node", self.collect_data)
        builder.add_node("formatter_node", self.format_output)

        builder.add_edge(START, "collect_data_node")
        builder.add_edge("collect_data_node", "formatter_node")
        builder.add_edge("formatter_node", END)

        self.graph = builder.compile()

    def collect_data(self, state: AgentMessagesState):
        """Deterministically collect data from all macro tools without an LLM."""
        
        tool_results = []
        
        def run_tool(tool):
            try:
                # Call tool directly using its underlying function
                # The LangChain @tool decorator wraps it, so we can use .invoke
                result = tool.invoke({})
                return tool.name, result
            except Exception as e:
                return tool.name, {"error": str(e)}
                
        with ThreadPoolExecutor(max_workers=len(TOOLS)) as executor:
            futures = [executor.submit(run_tool, t) for t in TOOLS]
            for future in as_completed(futures):
                name, result = future.result()
                # Create a pseudo-ToolMessage so the formatter can process it identically
                tool_results.append(
                    ToolMessage(
                        content=str(result),
                        name=name,
                        tool_call_id=f"deterministic_{name}"
                    )
                )
                
        return {"messages": tool_results}


    def format_output(self, state: AgentMessagesState):
        """Convert collected tool results into a validated MacroSummary."""
        from src.models.macro import MacroSummary
        
        messages = state["messages"]

        # 1. Deterministically build the raw market data dictionary.
        # Tools that return news articles are kept apart: they are context
        # for the LLM, not market data to store or print in the report.
        raw_market_data = {}
        news_articles = []
        for msg in messages:
            if msg.type == "tool":
                tool_name = msg.name.replace("get_", "").replace("_price", "").replace("_data", "").replace("_updates", "").replace("_summary", "").replace("_rate", "")
                
                # safely parse the raw string back to dict since it was converted to string in collect_data
                content = str(msg.content).strip()
                try:
                    # In python strings from dicts use single quotes, ast.literal_eval is safest
                    import ast
                    data = ast.literal_eval(content)
                except BaseException:
                    raw_market_data[tool_name] = {"error": "Failed to parse tool output"}
                    continue

                if isinstance(data, dict) and isinstance(data.get("articles"), list):
                    news_articles.extend(data["articles"])
                else:
                    raw_market_data[tool_name] = data

        # 2. Prepare the prompt for the reasoning LLM.
        # market_data and last_updated are excluded — they are attached
        # deterministically after the LLM call, not generated by the model
        # (asked for a timestamp, the model simply invents one).
        # escape_braces=False: this SystemMessage is an f-string, not a
        # ChatPromptTemplate, so braces must NOT be doubled here.
        json_instruction = build_json_instruction(
            MacroSummary, exclude_fields=("market_data", "last_updated"), escape_braces=False
        )

        tool_data_str = json.dumps(raw_market_data, indent=2)
        # Tavily and Firecrawl search the same news, so the same article can
        # arrive from both.
        news_str = self._format_news(deduplicate_article_dicts(news_articles))

        instruction = SystemMessage(
            content=f"""You are a financial market intelligence expert.

Your task is to analyze the provided macroeconomic data and generate a structured sentiment summary.

Rules:
- Do NOT call any tools.
- Do NOT invent information. Quote figures exactly as given.
- market_events: list only events explicitly mentioned in the data or news below. If none are mentioned, return an empty list.
- A missing or null data point means it was unavailable — do not assume a value for it.
{json_instruction}

Macroeconomic Data:

{tool_data_str}

Recent Macro News:

{news_str}
"""
        )

        # 3. Call the reasoning LLM (we only make ONE LLM call here)
        # Using self.formatter_llm as the reasoning LLM.
        response = self.formatter_llm.invoke([
            instruction,
            HumanMessage(content="Analyze the collected macroeconomic data and produce the required JSON sentiment summary.")
        ])

        content = str(response.content).strip()

        # 4. Diagnostic Error Handling
        if not content:
            model_info = getattr(self.formatter_llm, 'model', 'unknown model')
            prompt_len = len(instruction.content)
            raise ValueError(
                f"MacroAgent LLM Failure: The model '{model_info}' returned an entirely empty response.\n"
                f"This usually indicates a context length issue (prompt length: {prompt_len} chars) "
                f"or a model generation filter. Please try a different model or reduce data size."
            )

        # Defensive JSON parsing. raw_decode from the first '{' instead of a
        # greedy `\{.*\}` regex, which spans to the LAST '}' in the response
        # and pulls in any trailing text or a second malformed object.
        start = content.find("{")
        if start == -1:
            raise ValueError(
                f"Failed to parse JSON from MacroAgent LLM.\n"
                f"No JSON object found in response.\nResponse content:\n{content}"
            )
        try:
            data, _end = json.JSONDecoder().raw_decode(content, start)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Failed to parse JSON from MacroAgent LLM.\n"
                f"Error: {e}\n"
                f"Response content:\n{content}"
            ) from e

        data = unwrap_schema_echo(data)

        # 5. Deterministically attach the raw market data and timestamp
        data["market_data"] = raw_market_data
        data["last_updated"] = utc_now_iso()

        # 6. Validate
        try:
            result = MacroSummary.model_validate(data)
        except ValidationError as e:
            raise ValueError(
                f"MacroSummary validation failed.\n"
                f"Validation error: {e}\n"
                f"Parsed data: {data}"
            ) from e

        return {
            "final_result": result
        }

    @staticmethod
    def _format_news(articles: list) -> str:
        """Render collected news articles as a compact, dated list for the prompt."""
        lines = []
        for article in articles:
            if not isinstance(article, dict) or not article.get("title"):
                continue
            published = (article.get("published_at") or "undated")[:16]
            source = article.get("source") or "unknown source"
            lines.append(f"- [{published}] {article['title']} ({source})")
            if article.get("summary"):
                lines.append(f"  {article['summary']}")
        return "\n".join(lines) if lines else "No recent macro news available."

    def run(self) -> MacroSummary:
        """Run the macro intelligence agent."""
        initial_state: AgentMessagesState = {
            "messages": [],
            "final_result": None,
        }

        state = self.graph.invoke(initial_state)

        return state["final_result"]
