from typing import Optional
from pydantic import BaseModel, Field

from src.models.common import ConfidenceScore, StringList
from src.models.macro import MacroSummary
from src.models.sentiment import SentimentResult


class CompanyIntelligence(BaseModel):
    """
    Per-company intelligence section within the daily report.
    """

    ticker: str
    company_name: str

    # Overall sentiment label for this company.
    sentiment: str
    confidence: ConfidenceScore = Field(ge=0, le=100)

    # Key signals broken out by source type.
    key_positive_signals: StringList = Field(default_factory=list)
    key_negative_signals: StringList = Field(default_factory=list)

    # News headlines / top articles relevant to today.
    important_news: StringList = Field(default_factory=list)

    # Price, technical indicators and sector move from MarketDataAgent.
    market_snapshot: Optional[str] = None

    # Relevant financial context (PE, events, etc.) from FinancialDataAgent.
    financial_context: Optional[str] = None

    # Reddit / community signal (explicitly labeled as community source).
    reddit_community_signal: Optional[str] = None

    # How today's macro environment affects this company.
    macro_relevance: Optional[str] = None

    # Passages retrieved from the 20-year price-history store (src/rag).
    # Empty when the store is not configured.
    historical_context: StringList = Field(default_factory=list)

    # Final synthesised interpretation for this company.
    overall_interpretation: str = ""


class ChangeRow(BaseModel):
    """
    One line of the day-over-day comparison. Values are pre-formatted
    strings: the row is for display, built by ChangeDetectionService.
    """

    item: str
    previous: str
    current: str
    change: str


class CompanyNarrative(BaseModel):
    """
    LLM-written commentary for one company.
    """

    ticker: str = Field(description="Ticker exactly as given in the input")

    macro_relevance: str = Field(
        default="",
        description="One or two sentences on how today's macro environment affects this company",
    )

    overall_interpretation: str = Field(
        default="",
        description="Two or three sentences interpreting this company's signals",
    )


class ReportNarrative(BaseModel):
    """
    The part of the daily report the LLM writes: commentary only.

    Everything factual in DailyMarketReport (sentiment labels, drivers,
    headlines, prices, timestamps) is attached in code from the upstream
    agents' output. When the model was asked to return those too it retyped
    them, and altered figures in the process (e.g. "£130,000" came back as
    "Rs 13,00,000").
    """

    macro_overview: str = Field(
        default="",
        description="One paragraph on the current macro environment and its key risks",
    )

    company_narratives: list[CompanyNarrative] = Field(default_factory=list)

    final_market_view: str = Field(
        default="",
        description="One paragraph giving the overall market view",
    )

    major_catalysts: StringList = Field(default_factory=list)

    major_risks: StringList = Field(default_factory=list)


class DailyMarketReport(BaseModel):
    """
    Final report generated by the Report Agent.
    """

    date: str

    overall_market_sentiment: str

    overall_confidence: ConfidenceScore = Field(ge=0, le=100)

    # Full MacroSummary object for downstream use / serialisation.
    macro_summary: MacroSummary

    # Narrative macro overview for human readers.
    macro_overview: str = ""

    # Primary macro drivers (FII/DII, crude, USD/INR, US markets, etc.).
    key_macro_drivers: StringList = Field(default_factory=list)

    # Per-company intelligence sections.
    company_intelligence: list[CompanyIntelligence] = Field(default_factory=list)

    # Backward-compatible aggregate lists (used by existing pipeline display).
    top_positive_stocks: list[SentimentResult] = Field(default_factory=list)
    top_negative_stocks: list[SentimentResult] = Field(default_factory=list)

    # Important market events (earnings, RBI, government actions, etc.).
    market_events: StringList = Field(default_factory=list)

    # Price moves since the previous session's close.
    market_changes: list[ChangeRow] = Field(default_factory=list)

    # Sentiment / flow / rate changes since the previous pipeline run, and
    # that run's date. Empty and None when no earlier run has been saved.
    run_changes: list[ChangeRow] = Field(default_factory=list)
    previous_run_date: Optional[str] = None

    # Synthesised final market view and risk/catalyst assessment.
    final_market_view: str = ""
    major_catalysts: StringList = Field(default_factory=list)
    major_risks: StringList = Field(default_factory=list)

    # Commentary sentences the FactCheckAgent removed as unsupported, each
    # with its reason. An audit trail: not shown in the PDF.
    removed_claims: StringList = Field(default_factory=list)

    generated_at: str
