from pydantic import BaseModel, Field

from src.models.macro import MacroSummary
from src.models.sentiment import SentimentResult


class DailyMarketReport(BaseModel):
    """
    Final report generated by the Report Agent.
    """

    date: str

    overall_market_sentiment: str

    overall_confidence: int = Field(
        ge=0,
        le=100,
    )

    macro_summary: MacroSummary

    top_positive_stocks: list[SentimentResult] = Field(
        default_factory=list
    )

    top_negative_stocks: list[SentimentResult] = Field(
        default_factory=list
    )

    market_events: list[str] = Field(
        default_factory=list
    )

    generated_at: str